# GitHub reusable workflow for creating a release in Sentry.

on:
  workflow_call:
    inputs:
      environment:
        default: development
        description: Environment for the release
        type: string
      org:
        description: Sentry organization slug
        required: false
        type: string
      project:
        description: Sentry project slug
        required: false
        type: string
      sourcemaps-artifacts-name:
        description: Name of the sourcemap artifacts to download
        required: false
        type: string
      sourcemaps-path:
        description: Path (relative to working directory) to of the sourcemaps
        type: string
      version:
        description: Identifier that uniquely identifies the release
        required: false
        type: string
    secrets:
      sentry-auth-token:
        description: Sentry authentication token (if creating a release in Sentry)
        required: false
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      image: ${{ inputs.create-release && fromJSON(steps.metadata.outputs.json).tags[0] || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: Download artifacts
        if: ${{ inputs.sourcemaps-artifacts-name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.sourcemaps-artifacts-name }}
          path: ${{ inputs.sourcemaps-path }}
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry-auth-token }}
          SENTRY_ORG: ${{ inputs.org }}
          SENTRY_PROJECT: ${{ inputs.project }}
        with:
          environment: ${{ inputs.environment }}
          set_commits: skip
          sourcemaps: ./${{ inputs.sourcemaps-path }}
          version: ${{ inputs.version && inputs.version || github.sha }}
